language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
sudo: required
group: deprecated-2017Q2
before_install:
  - openssl req -x509 -newkey rsa:4096 -keyout test.pilosa.local.key -out test.pilosa.local.crt -days 3650 -nodes -subj "/C=US/ST=Texas/L=Austin/O=Pilosa/OU=Com/CN=test.pilosa.local"
  - wget https://s3.amazonaws.com/build.pilosa.com/pilosa-master-linux-amd64.tar.gz && tar xf pilosa-master-linux-amd64.tar.gz
  - ./pilosa-master-linux-amd64/pilosa server --metric.diagnostics=false -b https://:30101 -d https_data --cluster.disabled --tls.skip-verify --tls.certificate test.pilosa.local.crt --tls.key test.pilosa.local.key &
  - ./pilosa-master-linux-amd64/pilosa server --metric.diagnostics=false -d http_data &
install: "pip install -r requirements/main.txt -r requirements/test.txt coveralls"
script:
  - PILOSA_BIND="https://:30101" LEGACY_MODE_OFF=true make test-all
  - make cover
after_success:
  coveralls
